# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate device_tree

Name:           rust-device_tree
Version:        1.1.0
Release:        %autorelease
Summary:        Reads and parses Linux device tree images

License:        MIT
URL:            https://crates.io/crates/device_tree
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Reads and parses Linux device tree images.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
