# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate vm-allocator

Name:           rust-vm-allocator
Version:        0.1.0
Release:        %autorelease
Summary:        Helpers for allocating resources needed during the lifetime of a VM

License:        Apache-2.0 AND (Apache-2.0 OR BSD-3-Clause)
URL:            https://crates.io/crates/vm-allocator
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          vm-allocator-fix-metadata.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Helpers for allocating resources needed during the lifetime of a VM.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/images
%doc %{crate_instdir}/src/allocation_engine/DESIGN.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
