# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate cargo_toml

Name:           rust-cargo_toml
Version:        0.13.3
Release:        %autorelease
Summary:        Cargo.toml struct definitions for parsing with Serde

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/cargo_toml
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          cargo_toml-fix-metadata.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Cargo.toml struct definitions for parsing with Serde.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
